-- =========================================================
-- JA ORÇAMENTOS - BANCO DE DADOS
-- Cole tudo no SQL Editor do Supabase e execute uma vez.
-- =========================================================

create table if not exists public.materiais (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  unidade text not null,
  preco numeric(12,2) not null default 0
);

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  telefone text not null default ''
);

create table if not exists public.orcamentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  cliente_nome text not null,
  telefone text not null default '',
  tipo_servico text not null,
  quantidade integer not null default 1,
  largura numeric(10,2) not null default 0,
  altura numeric(10,2) not null default 0,
  observacoes text not null default '',
  area numeric(12,2) not null default 0,
  custo_material numeric(12,2) not null default 0,
  detalhes_materiais jsonb,
  status text not null default 'aberto',
  custo_mao_obra numeric(12,2) not null default 0,
  margem_percentual numeric(8,2) not null default 0,
  multiplicador numeric(8,2) not null default 2.2,
  preco_final numeric(12,2) not null default 0
);

-- Garante que bancos criados com uma versão anterior recebam as colunas novas.
alter table public.orcamentos add column if not exists custo_mao_obra numeric(12,2) not null default 0;
alter table public.orcamentos add column if not exists margem_percentual numeric(8,2) not null default 0;
alter table public.orcamentos add column if not exists multiplicador numeric(8,2) not null default 2.2;
alter table public.orcamentos add column if not exists preco_final numeric(12,2) not null default 0;

-- RLS: o sistema usa Supabase Auth. Somente usuários autenticados podem acessar os dados.
alter table public.materiais enable row level security;
alter table public.clientes enable row level security;
alter table public.orcamentos enable row level security;

drop policy if exists "materiais_select" on public.materiais;
drop policy if exists "materiais_insert" on public.materiais;
drop policy if exists "materiais_update" on public.materiais;
drop policy if exists "materiais_delete" on public.materiais;
create policy "materiais_select" on public.materiais for select to authenticated using (true);
create policy "materiais_insert" on public.materiais for insert to authenticated with check (true);
create policy "materiais_update" on public.materiais for update to authenticated using (true) with check (true);
create policy "materiais_delete" on public.materiais for delete to authenticated using (true);

drop policy if exists "clientes_select" on public.clientes;
drop policy if exists "clientes_insert" on public.clientes;
drop policy if exists "clientes_update" on public.clientes;
drop policy if exists "clientes_delete" on public.clientes;
create policy "clientes_select" on public.clientes for select to authenticated using (true);
create policy "clientes_insert" on public.clientes for insert to authenticated with check (true);
create policy "clientes_update" on public.clientes for update to authenticated using (true) with check (true);
create policy "clientes_delete" on public.clientes for delete to authenticated using (true);

drop policy if exists "orcamentos_select" on public.orcamentos;
drop policy if exists "orcamentos_insert" on public.orcamentos;
drop policy if exists "orcamentos_update" on public.orcamentos;
drop policy if exists "orcamentos_delete" on public.orcamentos;
create policy "orcamentos_select" on public.orcamentos for select to authenticated using (true);
create policy "orcamentos_insert" on public.orcamentos for insert to authenticated with check (true);
create policy "orcamentos_update" on public.orcamentos for update to authenticated using (true) with check (true);
create policy "orcamentos_delete" on public.orcamentos for delete to authenticated using (true);

-- Materiais-base. Se já existirem, não duplica.
insert into public.materiais (nome, unidade, preco)
select 'Tubo 30x30', 'barra 6m', 75
where not exists (select 1 from public.materiais where lower(replace(nome, '×', 'x')) = 'tubo 30x30');

insert into public.materiais (nome, unidade, preco)
select 'Tubo 20x30', 'barra 6m', 80
where not exists (select 1 from public.materiais where lower(replace(nome, '×', 'x')) = 'tubo 20x30');

insert into public.materiais (nome, unidade, preco)
select 'Trilho', 'metro', 0
where not exists (select 1 from public.materiais where lower(nome) = 'trilho');

insert into public.materiais (nome, unidade, preco)
select 'Tela', 'm²', 0
where not exists (select 1 from public.materiais where lower(nome) = 'tela');

insert into public.materiais (nome, unidade, preco)
select 'Rodinha', 'unidade', 0
where not exists (select 1 from public.materiais where lower(nome) = 'rodinha');

insert into public.materiais (nome, unidade, preco)
select 'Bate-fecha / bico de papagaio', 'unidade', 0
where not exists (select 1 from public.materiais where lower(nome) = 'bate-fecha / bico de papagaio');
